
### Add User
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "fullName": "Anuj Sharma",
    "phoneNumber": "7726062540",
    "email": "anujsharma11098@gmail.com",
    "password": "password"
}
### Login User
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email": "anujsharma11098@gmail.com",
    "password": "password"
}

### Get all Events

GET http://localhost:5000/api/createEvent

### event registered

POST http://localhost:5000/api/createEvent
Content-Type: application/json

{
    "authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wiX2lkXCI6XCI1ZWQ2N2I1ODE5M2FlYjA1Y2MxZmU4ZTJcIixcImZ1bGxOYW1lXCI6XCJBbnVqIFNoYXJtYVwiLFwicGhvbmVOdW1iZXJcIjo3NzI2MDYyNTQwLFwiZW1haWxcIjpcImFudWpzaGFybWExMTA5OEBnbWFpbC5jb21cIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkRFJUNEZtdkJJeUJleDc2RzZrdHZCdXJOWXc0R1hxclZPWHJQM1dLaC9MbEtDZjh1bnBhNjJcIixcImNyZWF0ZWRBdFwiOlwiMjAyMC0wNi0wMlQxNjoxNjoyNC4zOTFaXCIsXCJ1cGRhdGVkQXRcIjpcIjIwMjAtMDYtMDJUMTY6MTY6MjQuMzkxWlwiLFwiX192XCI6MH0iLCJpYXQiOjE1OTExMTQ1ODR9.xKbeWneGsT7LoginTSX2oCwPNAQHigo5w7sgpUDby_Q",
    "eventName" : "GDG",
    "venue":"pappu ka Ghar",
    "date" : "2020-06-20",
    "payment":"Free",
    "eventType":"writing"
}

### interested

POST http://localhost:5000/api/interested
Content-Type: application/json

{
    "eventId":"5ed68095251aaf2ab8ff0dec",
    "fullName":"Afzal",
    "email":"afzalraza@gmail.com",
    "registrationType":"SELF",
    "phoneNumber":"9024653005",
    "ticketCount":"1"
}

### get event Info by id

GET http://localhost:5000/api/interested/5ed68095251aaf2ab8ff0dec
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wiX2lkXCI6XCI1ZWQ2N2I1ODE5M2FlYjA1Y2MxZmU4ZTJcIixcImZ1bGxOYW1lXCI6XCJBbnVqIFNoYXJtYVwiLFwicGhvbmVOdW1iZXJcIjo3NzI2MDYyNTQwLFwiZW1haWxcIjpcImFudWpzaGFybWExMTA5OEBnbWFpbC5jb21cIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkRFJUNEZtdkJJeUJleDc2RzZrdHZCdXJOWXc0R1hxclZPWHJQM1dLaC9MbEtDZjh1bnBhNjJcIixcImNyZWF0ZWRBdFwiOlwiMjAyMC0wNi0wMlQxNjoxNjoyNC4zOTFaXCIsXCJ1cGRhdGVkQXRcIjpcIjIwMjAtMDYtMDJUMTY6MTY6MjQuMzkxWlwiLFwiX192XCI6MH0iLCJpYXQiOjE1OTExMTQ1ODR9.xKbeWneGsT7LoginTSX2oCwPNAQHigo5w7sgpUDby_Q
