
### Add User
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "fullName": "Anuj Sharma",
    "phoneNumber": "7726062540",
    "email": "anujsharma11098@gmail.com",
    "password": "password"
}
### Login User
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "email": "anujsharma11098@gmail.com",
    "password": "password"
}

### Get all Events

GET http://localhost:5000/api/eventRegistration
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wiX2lkXCI6XCI1ZWQwYjA4OGZlODczMTQzYWM4ZDBmZThcIixcImZ1bGxOYW1lXCI6XCJBbnVqIFNoYXJtYVwiLFwicGhvbmVOdW1iZXJcIjo3NzI2MDYyNTQwLFwiZW1haWxcIjpcImFudWpzaGFybWExMTA5OEBnbWFpbC5jb21cIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkSDF6QXN0WXF3bVh3ZVNFWXk2bXZpdTM3MG0vU0gxU3p0VE0uOFA0RGtQRmRvVkVqaEg5MW1cIixcImNyZWF0ZWRBdFwiOlwiMjAyMC0wNS0yOVQwNjo0OTo0NC40NTdaXCIsXCJ1cGRhdGVkQXRcIjpcIjIwMjAtMDUtMjlUMDY6NDk6NDQuNDU3WlwiLFwiX192XCI6MH0iLCJpYXQiOjE1OTA3MzQ5ODV9.2k3H2n6qSTR8Cq5-FA_x7DVbTaHK-EJmCT_TRNOqFDg

### event registered

POST http://localhost:5000/api/eventRegistration
Content-Type: application/json

{
    "authorization": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoie1wiX2lkXCI6XCI1ZWQwYjA4OGZlODczMTQzYWM4ZDBmZThcIixcImZ1bGxOYW1lXCI6XCJBbnVqIFNoYXJtYVwiLFwicGhvbmVOdW1iZXJcIjo3NzI2MDYyNTQwLFwiZW1haWxcIjpcImFudWpzaGFybWExMTA5OEBnbWFpbC5jb21cIixcInBhc3N3b3JkXCI6XCIkMmEkMTAkSDF6QXN0WXF3bVh3ZVNFWXk2bXZpdTM3MG0vU0gxU3p0VE0uOFA0RGtQRmRvVkVqaEg5MW1cIixcImNyZWF0ZWRBdFwiOlwiMjAyMC0wNS0yOVQwNjo0OTo0NC40NTdaXCIsXCJ1cGRhdGVkQXRcIjpcIjIwMjAtMDUtMjlUMDY6NDk6NDQuNDU3WlwiLFwiX192XCI6MH0iLCJpYXQiOjE1OTA3MzQ5ODV9.2k3H2n6qSTR8Cq5-FA_x7DVbTaHK-EJmCT_TRNOqFDg",
    "fullName" : "Anuj Sharma" ,
    "email" : "anujsharma11098@gmail.com" ,
    "phoneNumber" : "7726062540" ,
    "registrationType" : "GROUP" ,
    "ticketCount" : "100"
}